# Welcome to Jekyll!
#

# Site settings
title: Kotekad Plantation Stay in Coorg
description: |
  The Kotekad plantation stay is a place surrounded with nature and peace.   
  The feeling of being around in the Kotekad plantation seems like enjoying every inch of nature and its beauty.
owner: kotekad plantation # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: your-email@domain.com
#baseurl: ""
#url: ""
baseurl: "https://kotekad.github.io/website" # the subpath of your site, e.g. /blog
url: "https://kotekad.github.io/website/" # the base hostname & protocol for your site
social:
  phone: +91 96114 78283
  phone: +91 94482 06668
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: bruh@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
